spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        # - Header=token, \d+
        # - Method=GET, POST
        # - Query=color
        # - Cookie=color, azul
        # - Header=Content-Type, application/json
        filters:
        - StripPrefix=2
        - EjemploCookie=Hola mi mensaje personalizado para productos!, user, Andres
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, aabbsjdfjsaj
        - AddResponseHeader=token-response, 234340823
        - AddRequestParameter=name, Andres
        - SetResponseHeader=Content-Type, text/plain